### ISSUE TITLE
Not able to replicate the results

### ISSUE THREAD

**Issue by Jan21** [pbelcak/FastBERT#19]
Hi, 
we are trying to replicate the results presented in Table 1 of the paper.  We leave everything as is and pretrain the model with the following command: `python pretrain.py name=amp_b8192_cb_o4_final arch=crammed-bert-fff train=bert-o4  data=pile-readymade` It trains for 1 day on a single Nvidia A100
Then we evaluate it with: `python eval.py eval=GLUE_sane name=amp_b8192_cb_o4_final eval.checkpoint=latest impl.microbatch_size=16 impl.shuffle_in_dataloader=True impl.compile_torch=False`

We get average GLUE score of 74%.

We also tried to train a trasnformer with the FFF layer on TinyStories dataset. We take the original model and just replace the FF layers with FFF layers. We achieve the same perplexity as a model with the MLPs completely removed. The perplexity is worse than the one achieved by the original model with FF layers.

**Comment by pbelcak** [comment]
Hi,

Thanks for getting in touch.

"Replicate" is a bit of a stretch of the term here, since you differ on crucial parameters, including the hardware used (training is wallclock-capped) and CoLA finetuning parameters (note the adjustment made to the default as per section 2.3.1 of the paper).

1. How many tokens and epochs does your training consume? A100s in the crammedBERT setup are powerful enough to train on more than one epoch within a day, thus leading to overfitting, since crammedBERT has dropout disabled by default. What is your training token throughput?
2. What is your GLUE performance without CoLA? Did you include WNLI?

Here is a short list of things to work through to help you identify the problem, given in a particular order:

1. Download the weights from HF and finetune as per section 2.3. Are you getting results comparable to the ones in the paper? If yes, proceed.
2. Train a crammedBERT baseline on 3090/A6000. Are you getting results comparable to those of the original crammedBERT paper?
3. Train an UltraFastBERT baseline with branching depth set to 0. This is fully equivalent to crammedBERT since no activations are masked out. Are you getting results comparable to 3.?
4. Train UltraFastBERTs with increasing depths as in Table 1 of the UFB paper. Do your results align?

**Comment by Jan21** [comment]
Thank you for your quick response! We will try the steps you describe and let you know.

**Comment by Jan21** [comment]
Could you please give me instructions how to evaluate the checkpoint from HF? We tried to use the command for evaluation with the HF checkpoint mentioned in the training folder README but it does not work `python eval.py eval=rte name=bert-finetuning eval.checkpoint=hf://pbelcak/UltraFastBERT-1x11-long impl.shuffle_in_dataloader=True impl.compile_torch=False` 

It throws the following error: 
```
File "UltraFastBERT/training/eval.py", line 33, in main_downstream_process
    model = cramming.construct_model(cfg_arch, tokenizer.vocab_size, downstream_classes=task["num_classes"])
  File "UltraFastBERT/training/cramming/architectures/construction.py", line 41, in construct_model
    raise ValueError(f"Invalid model architecture {cfg_arch.architectures} given. Error: {e}")
ValueError: Invalid model architecture ['ScriptableLMForPreTraining'] given. Error: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
* (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
* (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
* 
```
I also checked the number of steps for training, it was 552000, not even 1 whole epoch.

**Comment by pbelcak** [comment]
The HF interface seems to be broken; you might want to debug it through that `try`-`except` in `construct.py` into `huggingface_interface.py` to see which tensor is not being initialized properly, and perhaps raise an issue [here](https://github.com/JonasGeiping/cramming) if it indeed just cramming-related.

Nevertheless, the HF interface is not needed. You can just download the weights (as mentioned in `1.` above) and run

```
python eval.py eval=EVAL_CONFIG name=NAME eval.checkpoint=CKPT_ABS_PATH OTHER_SETTINGS
```

`cramming.utils.find_pretrained_checkpoint` will retrieve the checkpoint for you and `cramming.construct_model` will then avoid the HF interface.

Note that this codebase does not modify the `cramming` codebase beyond altering the implementation of the feedforward layer, so when struggling with the CLI, it is always best to first try to do it for `cramming`.

> I also checked the number of steps for training, it was 552000, not even 1 whole epoch.

This does not say much, since cramming utilizes batch-size scheduling. If you use `wandb` for logging, what do `tok/sec` and `Charts/tokens` say? I found an older run that reached `14e9` tokens in roughly 21 hours on A100 80GB. That one was definitely overfitting.

**Comment by ssslakter** [comment]
Hi @pbelcak! I was also trying to evaluate the model to reproduce results from the paper. I've ran 
`python eval.py eval=rte name=bert-finetuning eval.checkpoint=hf://pbelcak/UltraFastBERT-1x11-long impl.shuffle_in_dataloader=True impl.compile_torch=False eval.batch_size=128`
 for RTE benchmark on model from HF unchanged, but got average 0.55 accuracy after 5 epochs. Maybe I'm using wrong batch size, though I didn't find it in the paper, what batch size did you use?

**Comment by pbelcak** [comment]
> Hi @pbelcak! I was also trying to evaluate the model to reproduce results from the paper. I've ran `python eval.py eval=rte name=bert-finetuning eval.checkpoint=hf://pbelcak/UltraFastBERT-1x11-long impl.shuffle_in_dataloader=True impl.compile_torch=False eval.batch_size=128` for RTE benchmark on model from HF unchanged, but got average 0.55 accuracy after 5 epochs. Maybe I'm using wrong batch size, though I didn't find it in the paper, what batch size did you use?

Oh dear, `128`? Please remember that most of the GLUE tasks have relatively small datasets and that comparatively small learning rates are to be used for pre-training. 128 is 4x the batch size of the original BERT and 8x the batch size of crammedBERT. It also means 4x/8x fewer update steps in 5 epochs, respectively.

As repeatedly stressed above and in the preprint, the training and evaluation are based on that of crammedBERT. See the first paragraph of section 5 of [the paper ](https://arxiv.org/pdf/2212.14034.pdf) for specific details.

The BERTology of GLUE evaluation dictates that you should take a median of 5 runs as the result; the individual results for RTE should be roughly between `58.8` and `60.3`. Also, when using the HF model directly, make sure that the weights are loaded into an instance of the `crammed-bert-fff` architecture, and not of the original `crammed-bert`. The latter can happen if you installed `cramming` in your environment before.

**Comment by ssslakter** [comment]
Thank you very much for the detailed response! I'll explore the cramming paper in more details.
I'm still learning, so batch size is not that intuitive to me and I might have overlooked such important details😅 Thanks!

**Comment by pbelcak** [comment]
Closing as stale. @Jan21 feel free to reopen if you encounter further issues.
